### ISSUE TITLE
animation gifがビルドされない

### ISSUE THREAD

**Issue by Hidetaro7** [tuqulore/website-boilerplate#201]
以下のメッセージが表示された
```
GIF output requires libvips with support for ImageMagick
```
調べてみると11tyのプロジェクトでこんなイシューが立っていた。
https://github.com/11ty/eleventy-img/issues/139#issuecomment-1049236505

**Comment by Hidetaro7** [comment]
"@11ty/eleventy-img": "^2.0.0"で解決しそう

**Comment by knokmki612** [comment]
https://github.com/11ty/eleventy-img/releases/tag/v1.1.0 v1.1.0 以降ということではありますね

**Comment by knokmki612** [comment]
現状v2.0.0が入っていますね

https://github.com/tuqulore/website-boilerplate/blob/531d8a44400d93eddd674cde98696428ebfb96bd/package.json#L14

> GIF output requires libvips with support for ImageMagick

eleventy-imgがImageMagick(sharp)に依存しておりlibvipsがgifの処理に必要なのだろうと思います
