### ISSUE TITLE
Windows環境でstyleのビルドに失敗する

### ISSUE THREAD

**Issue by Hidetaro7** [tuqulore/website-boilerplate#27]
`Input Error: You must pass a valid list of files to parse
error Command failed with exit code 1.`

ある一人の環境なので、すべてのWindows環境で起こるかかわらないが、`/style/style.css`にCSSファイルがビルドされない現象が起こっている。

@knokmki612

**Comment by knokmki612** [comment]
一般的に、UNIX系とWindowsではパス名の扱いが異なります。

具体的にはバス名の区切り文字がUNIX系ではスラッシュ `/` ですが、Windowsではバックスラッシュ `\` です。

エラーメッセージがどの処理を実行した際のメッセージか不明なのでなんとも言えませんが、eleventy、postcss-cliが(Globを使用した)パス指定についてWindowsを考慮していないことはありえます。

個人的にはWindows環境については[Windows Subsystem for Linux](https://docs.microsoft.com/ja-jp/windows/wsl/install-win10)上での利用をおすすめします。

**Comment by Hidetaro7** [comment]
Windows対応は今回見送るのでクローズ
